name: Build Check

on:
  push:
    branches:
      - main

jobs:
  build-macos:
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup dependencies
        run: |
          ./pull-deps.sh
          brew install openssl@3
          brew install llvm@16

      - name: Make
        run: make -f macos.mk

  build-android:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup dependencies
        run: ./pull-deps.sh

      - name: Make
        run: make -f android30.mk
