name: Build & Release Discovery Server

on:
  workflow_dispatch:
    inputs:
      version:
        description: Release version
        default: v1.0.0
        required: true

jobs:
  build-and-release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Build
        run: |
          ./build-linux.sh
          mv waterslide-ds-linux waterslide-ds-linux-${{ github.event.inputs.version }}
        working-directory: ./discovery-server

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          files: ./discovery-server/waterslide-ds-linux-${{ github.event.inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
